*** Variables ***
${referral}                     css=a[href="http://refer.cocowork.co/"]
${broker}                       css=a[href="http://broker.cocowork.co/"]
${blog}                         css=a[href="https://cohive.space/blogs/"]
${about-us}                     css=a[href="/about-us"]
${coliving}                     css=a[href="/coliving"]
${partnership}                  css=a[href="/partnership"]
${careers}                      css=a[href="https://www.jobstreet.co.id/en/job-search/jobs-at-cohive"]
${coliving-faq}                 css=a[href="/faq"]
${icon-linkin}                  css=a[href="https://www.linkedin.com/company/cocowork"]
${icon-ig}                      css=a[href="https://www.instagram.com/cohivespace/"]
${icon-fb}                      css=a[href="https://www.facebook.com/cohivespace"]
${icon-twitter}                 css=a[href="https://twitter.com/cohivespace"]
${input-subs}                   css=input[class="jsx-1263939812 form-control"]
${btn-subscribe}                id:subscribe-button